### ISSUE TITLE
Make herd rotations table more responsive

### ISSUE THREAD

**Issue by mstenta** [farmOS/farm_grazing#1]
The rotations table currently dynamically generates fixed-width images to visualize the rotations of herds (in /farm/plan/%/herds/rotations).

This does not scale down well on smaller screens because the images are always the same width.

Todo: explore options for improving the responsive quality of these visualizations.

**Comment by woodbri** [comment]
Some initial work on this has been done in branch "responsive-table" https://github.com/mstenta/farm_grazing/tree/responsive-table

This is based on using SVG images rather than PNG and setting them up to be scaleable. There is currently problems on the iPhone:

- the image header disappears
- and the last three columns overlay on top of the images

No sure what these issues are but we will look into them. Also planning to convert the last three columns into a single "Operations" column with three fields separated with a "|" to save on layout space.

**Comment by mstenta** [comment]
Merged Steve's branch.
